title: QuanTech Consulting Ltd
description: Professional Operational Transformation & Strategic Management Consulting Solutions
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
